//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.DBModel {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Game", Namespace="http://schemas.datacontract.org/2004/07/GameStoreModelService")]
    [System.SerializableAttribute()]
    public partial class Game : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GameIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlatformField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GameID {
            get {
                return this.GameIDField;
            }
            set {
                if ((this.GameIDField.Equals(value) != true)) {
                    this.GameIDField = value;
                    this.RaisePropertyChanged("GameID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageData {
            get {
                return this.ImageDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageDataField, value) != true)) {
                    this.ImageDataField = value;
                    this.RaisePropertyChanged("ImageData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Platform {
            get {
                return this.PlatformField;
            }
            set {
                if ((object.ReferenceEquals(this.PlatformField, value) != true)) {
                    this.PlatformField = value;
                    this.RaisePropertyChanged("Platform");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShippingInformation", Namespace="http://schemas.datacontract.org/2004/07/GameStoreModelService")]
    [System.SerializableAttribute()]
    public partial class ShippingInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CartInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShippingInformationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetAndHouseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CartInfo {
            get {
                return this.CartInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.CartInfoField, value) != true)) {
                    this.CartInfoField = value;
                    this.RaisePropertyChanged("CartInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShippingInformationID {
            get {
                return this.ShippingInformationIDField;
            }
            set {
                if ((this.ShippingInformationIDField.Equals(value) != true)) {
                    this.ShippingInformationIDField = value;
                    this.RaisePropertyChanged("ShippingInformationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetAndHouse {
            get {
                return this.StreetAndHouseField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetAndHouseField, value) != true)) {
                    this.StreetAndHouseField = value;
                    this.RaisePropertyChanged("StreetAndHouse");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Login", Namespace="http://schemas.datacontract.org/2004/07/GameStoreModelService")]
    [System.SerializableAttribute()]
    public partial class Login : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoginIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoginID {
            get {
                return this.LoginIDField;
            }
            set {
                if ((this.LoginIDField.Equals(value) != true)) {
                    this.LoginIDField = value;
                    this.RaisePropertyChanged("LoginID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DBModel.IGameStoreService")]
    public interface IGameStoreService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/Games", ReplyAction="http://tempuri.org/IGameStoreService/GamesResponse")]
        GameStore.DBModel.Game[] Games();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/Games", ReplyAction="http://tempuri.org/IGameStoreService/GamesResponse")]
        System.Threading.Tasks.Task<GameStore.DBModel.Game[]> GamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/SaveGame", ReplyAction="http://tempuri.org/IGameStoreService/SaveGameResponse")]
        void SaveGame(GameStore.DBModel.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/SaveGame", ReplyAction="http://tempuri.org/IGameStoreService/SaveGameResponse")]
        System.Threading.Tasks.Task SaveGameAsync(GameStore.DBModel.Game game);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/DeleteGame", ReplyAction="http://tempuri.org/IGameStoreService/DeleteGameResponse")]
        GameStore.DBModel.Game DeleteGame(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/DeleteGame", ReplyAction="http://tempuri.org/IGameStoreService/DeleteGameResponse")]
        System.Threading.Tasks.Task<GameStore.DBModel.Game> DeleteGameAsync(int gameID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/ShippingInformations", ReplyAction="http://tempuri.org/IGameStoreService/ShippingInformationsResponse")]
        GameStore.DBModel.ShippingInformation[] ShippingInformations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/ShippingInformations", ReplyAction="http://tempuri.org/IGameStoreService/ShippingInformationsResponse")]
        System.Threading.Tasks.Task<GameStore.DBModel.ShippingInformation[]> ShippingInformationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/SaveShippingInformation", ReplyAction="http://tempuri.org/IGameStoreService/SaveShippingInformationResponse")]
        void SaveShippingInformation(GameStore.DBModel.ShippingInformation shippingInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/SaveShippingInformation", ReplyAction="http://tempuri.org/IGameStoreService/SaveShippingInformationResponse")]
        System.Threading.Tasks.Task SaveShippingInformationAsync(GameStore.DBModel.ShippingInformation shippingInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/DeleteShippingInfo", ReplyAction="http://tempuri.org/IGameStoreService/DeleteShippingInfoResponse")]
        GameStore.DBModel.ShippingInformation DeleteShippingInfo(int shippingInfoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/DeleteShippingInfo", ReplyAction="http://tempuri.org/IGameStoreService/DeleteShippingInfoResponse")]
        System.Threading.Tasks.Task<GameStore.DBModel.ShippingInformation> DeleteShippingInfoAsync(int shippingInfoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/Logins", ReplyAction="http://tempuri.org/IGameStoreService/LoginsResponse")]
        GameStore.DBModel.Login[] Logins();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGameStoreService/Logins", ReplyAction="http://tempuri.org/IGameStoreService/LoginsResponse")]
        System.Threading.Tasks.Task<GameStore.DBModel.Login[]> LoginsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameStoreServiceChannel : GameStore.DBModel.IGameStoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameStoreServiceClient : System.ServiceModel.ClientBase<GameStore.DBModel.IGameStoreService>, GameStore.DBModel.IGameStoreService {
        
        public GameStoreServiceClient() {
        }
        
        public GameStoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GameStoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameStoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GameStoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GameStore.DBModel.Game[] Games() {
            return base.Channel.Games();
        }
        
        public System.Threading.Tasks.Task<GameStore.DBModel.Game[]> GamesAsync() {
            return base.Channel.GamesAsync();
        }
        
        public void SaveGame(GameStore.DBModel.Game game) {
            base.Channel.SaveGame(game);
        }
        
        public System.Threading.Tasks.Task SaveGameAsync(GameStore.DBModel.Game game) {
            return base.Channel.SaveGameAsync(game);
        }
        
        public GameStore.DBModel.Game DeleteGame(int gameID) {
            return base.Channel.DeleteGame(gameID);
        }
        
        public System.Threading.Tasks.Task<GameStore.DBModel.Game> DeleteGameAsync(int gameID) {
            return base.Channel.DeleteGameAsync(gameID);
        }
        
        public GameStore.DBModel.ShippingInformation[] ShippingInformations() {
            return base.Channel.ShippingInformations();
        }
        
        public System.Threading.Tasks.Task<GameStore.DBModel.ShippingInformation[]> ShippingInformationsAsync() {
            return base.Channel.ShippingInformationsAsync();
        }
        
        public void SaveShippingInformation(GameStore.DBModel.ShippingInformation shippingInformation) {
            base.Channel.SaveShippingInformation(shippingInformation);
        }
        
        public System.Threading.Tasks.Task SaveShippingInformationAsync(GameStore.DBModel.ShippingInformation shippingInformation) {
            return base.Channel.SaveShippingInformationAsync(shippingInformation);
        }
        
        public GameStore.DBModel.ShippingInformation DeleteShippingInfo(int shippingInfoID) {
            return base.Channel.DeleteShippingInfo(shippingInfoID);
        }
        
        public System.Threading.Tasks.Task<GameStore.DBModel.ShippingInformation> DeleteShippingInfoAsync(int shippingInfoID) {
            return base.Channel.DeleteShippingInfoAsync(shippingInfoID);
        }
        
        public GameStore.DBModel.Login[] Logins() {
            return base.Channel.Logins();
        }
        
        public System.Threading.Tasks.Task<GameStore.DBModel.Login[]> LoginsAsync() {
            return base.Channel.LoginsAsync();
        }
    }
}
